.\"
.\"Copyright (c) 2021 Sean Davies <sean@city17.org>
.\"
.\"Permission to use, copy, modify, and distribute this software for any
.\"purpose with or without fee is hereby granted, provided that the above
.\"copyright notice and this permission notice appear in all copies.
.\"
.\"THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\"WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\"MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\"ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\"WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\"ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\"OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: February 7 2021 $
.Dt TARSNAPS 8
.Os
.Sh NAME
.Nm tarsnaps
.Nd automate tarsnap backups
.Sh SYNOPSIS
.Nm
.Op Fl d Ar max Fl m Ar max Fl w Ar max
.Ar target ...
.Nm
.Fl v
.Sh DESCRIPTION
.Nm
is a utility that is designed to be run once a day from
.Xr cron 8
and creates a
.Xr tarsnap 1
backup of the files or directories passed as
.Ar target .
Weekly and monthly archives are created automatically when a daily backup is
taken, and the day matches a
.Em Sunday
or the
.Em 1st
of the month, respectively.
.Pp
The maximum number of stored archives can be set individually for the daily,
weekly, and monthly backups by specifying the
.Ar max
value for each.
Once the number of stored archives exceeds this value the oldest are deleted
first.
.Pp
If
.Ar max
if not defined, then all archives are stored.
If
.Ar max
is defined as
.Cm 0
then the backup, if applicable, is not taken and any stored archives
are deleted.
If all values for
.Ar max
are defined as
.Cm 0
then all archives created by
.Nm
are deleted, the user is prompted to confirm this action before
continuing.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d Ar max
Maximum number of daily archives to keep.
.It Fl m Ar max
Maximum number of monthly archives to keep.
.It Fl v
Display version information and exit.
.It Fl w Ar max
Maximum number of weekly archives to keep.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
The following are example
.Xr crontab 5
entries of a daily backup.
.Pp
Keep 10 daily, 6 weekly and 12 monthly archives.
.Bd -literal -offset indent
0 22 * * * /usr/local/bin/tarsnaps -d 10 -w 6 -m 12 /etc /home
.Ed
.Pp
Keep 28 daily, no weekly and all monthly archives.
.Bd -literal -offset indent
0 22 * * * /usr/local/bin/tarsnaps -d 28 -w 0 /etc /home
.Ed
.Sh SEE ALSO
.Xr tarsnap 1 ,
.Xr crontab 5 ,
.Xr tarsnap.conf 5 ,
.Xr cron 8
.Sh AUTHORS
.An Sean Davies Aq Mt sean@city17.org
.Sh CAVEATS
All items to be backed up should be included in a single job.
.Nm
assumes it is only being run once per host and does not distinguish between
archives created with different input.
